version: "3"

services:
  database:
    image: postgres:10
    container_name: dota_db_container
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=data
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin

  dota:
    build: .
    image: dota_image:latest
    container_name: dota_container
    depends_on:
    - database
    ports:
    - 8080:8080
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/data
    - SPRING_DATASOURCE_USERNAME=admin
    - SPRING_DATASOURCE_PASSWORD=admin