version: "3.8"

services:
  database:
    image: postgres:10
    container_name: dota_db_container
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=data
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin
    networks:
    - dota-network

  dota:
    build: .
    image: dota_image:latest
    depends_on:
    - database
    expose:
    - 8080
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/data
    - SPRING_DATASOURCE_USERNAME=admin
    - SPRING_DATASOURCE_PASSWORD=admin
    networks:
    - dota-network

  nginx:
    image: nginx:latest
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - dota
    ports:
    - 4000:4000
    networks:
    - dota-network

networks:
  dota-network: