server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: dota

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/data
    username: admin
    password: admin
    initialization-mode: always
    schema: classpath:schema.sql

  liquibase:
    changeLog: classpath:db/changelog/db.changelog-master.xml
    default-schema: dota
